language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.1

sudo: false

cache: pip

before_install:
  - pip install --upgrade pip

install: 
    - pip install doc8
    - npm install -g write-good

script:
    - doc8 README.rst
    - write-good README.rst --so --thereIs --cliches
